name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend:
    name: Backend - Python Checks
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.12]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-txt.txt

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 . --max-line-length=88

      - name: Format check with black
        run: |
          pip install black
          black --check .

      - name: Run unit tests
        run: |
          pip install pytest
          pytest

  security:
    name: Python Security Audit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install safety and check vulnerabilities
        run: |
          pip install -r requirements-txt.txt
          pip install safety
          safety check --full-report
